name: Model-CI-Docker-Push

on:
  push:
    branches: [ main ]

jobs:
  train-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install mlflow pandas scikit-learn

      - name: Run MLflow Project (Training)
        run: |
          mlflow run ./MLProject --env-manager local

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          echo "Listing MLProject/mlruns:"
          ls -R MLProject/mlruns

          # Ambil RUN_ID terbaru
          RUN_ID=$(ls -td MLProject/mlruns/0/*/ | head -n 1 | xargs basename)

          MODEL_PATH="MLProject/mlruns/0/$RUN_ID/artifacts/model"
          IMAGE="${{ secrets.DOCKER_USERNAME }}/heart-disease-ci:latest"

          echo "RUN_ID=$RUN_ID"
          echo "MODEL_PATH=$MODEL_PATH"

          mlflow models build-docker \
            -m "$MODEL_PATH" \
            -n "$IMAGE" \
            --install-mlflow

          docker push "$IMAGE"

      - name: Push Versioned Tag (Docker Hub UI FIX)
        run: |
          VERSION="${{ secrets.DOCKER_USERNAME }}/heart-disease-ci:${{ github.sha }}"

          docker tag \
            ${{ secrets.DOCKER_USERNAME }}/heart-disease-ci:latest \
            "$VERSION"

          docker push "$VERSION"
