name: Model-CI-Docker-Push

on:
  push:
    branches: [ main ]

jobs:
  train-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install mlflow pandas scikit-learn

      - name: Run MLflow Project (Training)
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          mlflow run ./MLProject --env-manager local

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image (STABLE)
        run: |
          # ðŸ”‘ Ambil run TERBARU secara deterministik
          MODEL_PATH="./MLProject/mlruns/0/$(ls -t MLProject/mlruns/0 | head -n 1)/artifacts/model"

          IMAGE="${{ secrets.DOCKER_USERNAME }}/heart-disease-ci:latest"

          # Build image dengan TAG
          mlflow models build-docker \
            -m "$MODEL_PATH" \
            -n "$IMAGE" \
            --install-mlflow

          # Push TAG
          docker push "$IMAGE"

      - name: Push Versioned Tag (UI Trigger)
        run: |
          VERSION_TAG="${{ secrets.DOCKER_USERNAME }}/heart-disease-ci:${{ github.sha }}"

          docker tag \
            ${{ secrets.DOCKER_USERNAME }}/heart-disease-ci:latest \
            "$VERSION_TAG"

          docker push "$VERSION_TAG"
